### ISSUE TITLE
How i can remove hidden files button

### ISSUE THREAD

**Issue by LfJohnVo** [alexusmai/laravel-file-manager#212]
![image](https://user-images.githubusercontent.com/32848900/99436948-630fed80-28d7-11eb-8a51-015f99be13ff.png)

**Comment by LfJohnVo** [comment]
How i can remove?

**Comment by LfJohnVo** [comment]
Can you help me?

**Comment by vahidalvandi** [comment]
> How i can remove?

xx

**Comment by mansoorkhan96** [comment]
> How i can remove?

To remove this button, You need to edit the file-manager.js and remove the code for this button.

**Comment by BRAiNCHiLD95** [comment]
@LfJohnVo 

The easiest fix is to remove it via Javascript immediately after the file manager is loaded. If you do it properly, the button will be visible for less than a second.

A jQuery example -
// This will remove the Hidden files button.
$(document).find('div.fm').find('.fm-navbar').find('button[title=" Hidden files"]').remove();

If you don't use jQuery, you can very easily recreate this in JS (using document.querySelector() ).

Note the space before " Hidden" - you **need** that. It's actually a small typo on the internal code for the project. So you could do 2 lines, one with the space, and one without - and in the future - if the typo gets fixed, you're still good to go!

A harder (to maintain) fix is editing file-manager.js - because when the package gets updated, you'll have to redo everything you did to the already obfuscated & minified js file.

**Comment by daydevelops** [comment]
Using CSS:
```
button[title=' Hidden files'] {
    display:none;
}
```

**Comment by LfJohnVo** [comment]
> Using CSS:
> 
> ```
> button[title=' Hidden files'] {
>     display:none;
> }
> ```

Awesome!
